name: daily-update

on:
  schedule:
    - cron: '0 12 * * *'   # täglich 12:00 UTC
  workflow_dispatch: {}     # erlaubt manuelles Ausführen

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # wichtig für Push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yfinance pandas

      - name: Run fetch script
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python scripts/fetch_data.py
          
      - name: Commit and push data
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add data/data.json || true
          if ! git diff --quiet --cached; then
            git commit -m "daily data update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push https://$PAT_TOKEN@github.com/${{ github.repository }} HEAD:main
          else
            echo 'No changes to commit'
          fi
